### ISSUE TITLE
permission denied to create extension "uuid-ossp"

### ISSUE THREAD

**Issue by idkjs** [ecliptic/reason-graphql-docker#3]
If you follow the commands in the readme, you end up with the following error.

```
permission denied to create extension "uuid-ossp"
```
Cant seem to find how to set this permission. PostGres Rookie here.

- full error
```
$ dotenv knex migrate:latest
Knex:warning - migration file "20170101000000_initial.js" failed
Knex:warning - migration failed with error: CREATE EXTENSION IF NOT EXISTS "uuid-ossp"; - permission denied to create extension "uuid-ossp"
error: permission denied to create extension "uuid-ossp"
    at Connection.parseE (/Users/prisc_000/code/GRAPHQL/reason-graphql-docker/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/prisc_000/code/GRAPHQL/reason-graphql-docker/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/Users/prisc_000/code/GRAPHQL/reason-graphql-docker/node_modules/pg/lib/connection.js:113:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)
error Command failed with exit code 1.
```

Can you point me in the right direction? Thank you. Great right up, by the way. New to knex/postgres and that is killing me but totally worth it for your explanations on object/record conversions.

Thanks again.

**Comment by idkjs** [comment]
And the answer is:
To use uuid-ossp project run the following where first command is your database name and -c arg is the command and the extenstion you want to install.
`$ psql reason_graphql_docker -c 'CREATE EXTENSION "uuid-ossp";'`

**Comment by idkjs** [comment]
I take that back. Script seems to be running but not seeding the db
 
This is what i have done.

### Database Setup

Create a local `.env` file (required by `dotenv-cli`):

    $ touch .env

```env
DATABASE_HOSTNAME=127.0.0.1
DATABASE_NAME=reason-graphql-docker
DATABASE_USERNAME=reason-graphql-docker
DATABASE_PASSWORD=reason-graphql-docker
DATABASE_PORT=5432
```

Set up a local database:

```bsh
 createuser --interactive reason-graphql-docker
Shall the new role be a superuser? (y/n) y
PrisBook:reason-graphql-docker$[master *] createdb reason-graphql-docker -O reason-graphql-docker
PrisBook:reason-graphql-docker$[master *] psql -U reason-graphql-docker -d reason-graphql-docker -c 'CREATE EXTENSION "uuid-ossp";'
CREATE EXTENSION
PrisBook:reason-graphql-docker$[master *] yarn migrateyarn run v1.3.2
$ dotenv knex migrate:latest
Batch 1 run: 1 migrations
/Users/prisc_000/code/GRAPHQL/reason-graphql-docker/migrations/20170101000000_initial.js
✨  Done in 0.71s.
```
